In [1]:
cd /content/drive/MyDrive/김원/Colab_Notebooks

/content/drive/MyDrive/김원/Colab_Notebooks

In [2]:
!pip install datasets

Collecting datasets
  Downloading datasets-2.20.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets) (3.15.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (1.26.4)
Collecting pyarrow>=15.0.0 (from datasets)
  Downloading pyarrow-17.0.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets) (0.6)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (2.1.4)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.10/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.10/dist-packages (from datasets) (4.66.5)
Collecting xxhash (from datasets)
  Downloading xxhash-3.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess (from datasets)
  Downloading multiprocess-0.70.16-py310-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.5.0,>=2023.1.0 (from fsspec[http]<=2024.5.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.5.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.10.1)
Requirement already satisfied: huggingface-hub>=0.21.2 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.23.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (6.0.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (2.3.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (24.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.2->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2024.7.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Downloading datasets-2.20.0-py3-none-any.whl (547 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.8/547.8 kB 25.8 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 8.9 MB/s eta 0:00:00
Downloading fsspec-2024.5.0-py3-none-any.whl (316 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.1/316.1 kB 21.2 MB/s eta 0:00:00
Downloading pyarrow-17.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (39.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.9/39.9 MB 48.1 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 10.9 MB/s eta 0:00:00
Downloading xxhash-3.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 14.8 MB/s eta 0:00:00
Installing collected packages: xxhash, pyarrow, fsspec, dill, multiprocess, datasets
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 14.0.2
    Uninstalling pyarrow-14.0.2:
      Successfully uninstalled pyarrow-14.0.2
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.6.1
    Uninstalling fsspec-2024.6.1:
      Successfully uninstalled fsspec-2024.6.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.3.1+cu121 requires nvidia-cublas-cu12==12.1.3.1; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cuda-cupti-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cuda-nvrtc-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cuda-runtime-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cudnn-cu12==8.9.2.26; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cufft-cu12==11.0.2.54; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-curand-cu12==10.3.2.106; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cusolver-cu12==11.4.5.107; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cusparse-cu12==12.1.0.106; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-nccl-cu12==2.20.5; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-nvtx-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
cudf-cu12 24.4.1 requires pyarrow<15.0.0a0,>=14.0.1, but you have pyarrow 17.0.0 which is incompatible.
gcsfs 2024.6.1 requires fsspec==2024.6.1, but you have fsspec 2024.5.0 which is incompatible.
ibis-framework 8.0.0 requires pyarrow<16,>=2, but you have pyarrow 17.0.0 which is incompatible.
Successfully installed datasets-2.20.0 dill-0.3.8 fsspec-2024.5.0 multiprocess-0.70.16 pyarrow-17.0.0 xxhash-3.4.1

In [3]:
!pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.2-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.20.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from evaluate) (1.26.4)
Requirement already satisfied: dill in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.1.4)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.10/dist-packages (from evaluate) (4.66.5)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from evaluate) (3.4.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2024.5.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.23.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from evaluate) (24.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (3.15.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (17.0.0)
Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (0.6)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (3.10.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (2024.7.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2024.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.3.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (24.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (4.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.16.0)
Downloading evaluate-0.4.2-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 6.6 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.2

In [4]:
import torch
from datasets import load_dataset
from transformers import(
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    pipeline
)
import pandas as pd
import numpy as np
import evaluate

In [5]:
dataset = load_dataset('sepidmnorozy/Korean_sentiment')
dataset

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Downloading data:   0%|          | 0.00/3.29M [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/127k [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/239k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/36000 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1333 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2667 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['label', 'text'],
        num_rows: 36000
    })
    validation: Dataset({
        features: ['label', 'text'],
        num_rows: 1333
    })
    test: Dataset({
        features: ['label', 'text'],
        num_rows: 2667
    })
})

In [6]:
print(dataset['train'][3118])
print(dataset['train'][14310])

{'label': 1, 'text': '졸잼!!!성아가나중에억울한일이잇어서좀슬펏는데마지막은기쁘게끝나서다행이에여'}
{'label': 0, 'text': '진짜 어떻게 된놈의 영화가 여고괴담 1보다도 못함? 신기하다 그것도 2012년작이 1998년보다 못함 솔까 여고괴담1은 반전은 최고지 뭐 이놈의 영화는 여고괴담 시리즈보다도 못하는거같다'}

In [7]:
model_name = 'kykim/bert-kor-base'
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer

tokenizer_config.json:   0%|          | 0.00/80.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/725 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/344k [00:00<?, ?B/s]

BertTokenizerFast(name_or_path='kykim/bert-kor-base', vocab_size=42000, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	3: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	4: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}

In [8]:
def tokenizer_func(x):
    return tokenizer(
        x['text'],
        padding='max_length',
        max_length=256,
        truncation=True
    )

In [9]:
tokenized_datasets = dataset.map(tokenizer_func, batched=True)

Map:   0%|          | 0/36000 [00:00<?, ? examples/s]

Map:   0%|          | 0/1333 [00:00<?, ? examples/s]

Map:   0%|          | 0/2667 [00:00<?, ? examples/s]

In [10]:
train_num_samples = 10000

train_ds = tokenized_datasets['train'].shuffle(seed=42).select(range(train_num_samples))
eval_ds = tokenized_datasets['validation'].shuffle(seed=42)

# 전이학습 Transfer Learning

In [11]:
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

pytorch_model.bin:   0%|          | 0.00/476M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at kykim/bert-kor-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

# HyperParams

In [12]:
bs = 32
epochs = 4
lr = 1e-5

In [13]:
args = TrainingArguments(
    'outputs',
    learning_rate = lr,
    warmup_ratio = 0.1,
    lr_scheduler_type = 'cosine',
    fp16 = True,
    evaluation_strategy='epoch',
    per_device_train_batch_size = bs,
    per_device_eval_batch_size = bs,
    gradient_accumulation_steps=4, #until bs =128
    eval_accumulation_steps = 4,
    num_train_epochs=epochs,
    weight_decay=0.01,
    report_to = 'none'
)

/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

# Metrics

In [14]:
metric = evaluate.load('accuracy')

# all Transformers models retrun logits
def compute_metrics(eval_pred):
    logits, labels =eval_pred
    preds = np.argmax(logits, axis=-1)
    return metric.compute(predictions=preds, references=labels)

Downloading builder script:   0%|          | 0.00/4.20k [00:00<?, ?B/s]

In [15]:
class CustomTrainer(Trainer):
    def _save_checkpoint(self, model, trial, metrics=None):
        # 모델을 저장하기 전에 모든 텐서를 contiguous로 만듦
        for name, param in model.named_parameters():
            if param is not None:
                param.data = param.data.contiguous()
                if param.grad is not None:
                    param.grad.data = param.grad.data.contiguous()
        super()._save_checkpoint(model, trial, metrics)

# Trainer

In [16]:
trainer = CustomTrainer(
    model,
    args,
    train_dataset=train_ds,
    eval_dataset=eval_ds,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

In [17]:
trainer.train()

TrainOutput(global_step=312, training_loss=0.34380868765024036, metrics={'train_runtime': 149.2031, 'train_samples_per_second': 268.091, 'train_steps_per_second': 2.091, 'total_flos': 5247486888099840.0, 'train_loss': 0.34380868765024036, 'epoch': 3.987220447284345})

In [ ]:
trainer.save_model('./preprocess_transformer_model')

In [18]:
pipe = pipeline('text-classification', model='./preprocess_transformer_model')

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

# 테스트셋 사용

In [ ]:
test_data = dataset['validation'].shuffle(seed=424)[:100]
td = pd.DataFrame(test_data)
td

    label                                               text
0       1  비밀은 적정선에 관한 이야기이기도 하다. 사람에게 돈이란, 평판이란, 책임이란, 기...
1       0  메인 시나리오 뼈대가 없고 보여주기라기엔 용과의 전투씬도 너무 부족함..더욱이 결말...
2       1                  올??? 찌질한 스커드가 노만 리더스 행님이었다니 !! ㅋㅋ
3       0                 5점이 적당하나 평점이 쓸데없이 높아서 낮출 필요가 있슴...
4       0    연출, 기획, 스토리 전부다 쓰레기..제인생 영화중에 제일 쓰레기.. 절대보지마요진심
..    ...                                                ...
95      1                         """철아 엄마가 꼭 니 신세 갚고 죽을께"""
96      0                                     이건 뭐 .. 완전 삼류네
97      0  으... 밑도 끝도 없음. 여자가 처음부터 자기혈청을 제공했으면 카오스가 안왔을거 아님?
98      0  요즘에 보기에는 상당히 지루한 진부한 스릴러. 원초적 본능을 뛰어 넘기에도 힘든 영...
99      1       스토리,웃음,연기면에서 다 좋았습니다. 근데 리뷰보면 평가절하가 되어있는듯...

[100 rows x 2 columns]

In [ ]:
preds = pipe(td['text'].tolist())

preds_df = pd.DataFrame(preds)
preds_df

      label     score
0   LABEL_1  0.977509
1   LABEL_0  0.987574
2   LABEL_0  0.929627
3   LABEL_1  0.638549
4   LABEL_0  0.987248
..      ...       ...
95  LABEL_1  0.720594
96  LABEL_0  0.985785
97  LABEL_0  0.961799
98  LABEL_0  0.987525
99  LABEL_1  0.942406

[100 rows x 2 columns]

In [ ]:
preds_df.rename(columns={'label':'pred'}, inplace=True)
preds_df['pred'] = preds_df['pred'].map({'LABEL_1': 1, 'LABEL_0':0})

preds_df = pd.concat([preds_df, td], axis=1)
preds_df

    pred     score  label                                               text
0      1  0.977509      1  비밀은 적정선에 관한 이야기이기도 하다. 사람에게 돈이란, 평판이란, 책임이란, 기...
1      0  0.987574      0  메인 시나리오 뼈대가 없고 보여주기라기엔 용과의 전투씬도 너무 부족함..더욱이 결말...
2      0  0.929627      1                  올??? 찌질한 스커드가 노만 리더스 행님이었다니 !! ㅋㅋ
3      1  0.638549      0                 5점이 적당하나 평점이 쓸데없이 높아서 낮출 필요가 있슴...
4      0  0.987248      0    연출, 기획, 스토리 전부다 쓰레기..제인생 영화중에 제일 쓰레기.. 절대보지마요진심
..   ...       ...    ...                                                ...
95     1  0.720594      1                         """철아 엄마가 꼭 니 신세 갚고 죽을께"""
96     0  0.985785      0                                     이건 뭐 .. 완전 삼류네
97     0  0.961799      0  으... 밑도 끝도 없음. 여자가 처음부터 자기혈청을 제공했으면 카오스가 안왔을거 아님?
98     0  0.987525      0  요즘에 보기에는 상당히 지루한 진부한 스릴러. 원초적 본능을 뛰어 넘기에도 힘든 영...
99     1  0.942406      1       스토리,웃음,연기면에서 다 좋았습니다. 근데 리뷰보면 평가절하가 되어있는듯...

[100 rows x 4 columns]

In [ ]:
mask = preds_df['pred'] == preds_df['label']
len(preds_df[mask])

88

# 긍/부정 예측이 필요한 데이터셋

In [19]:
file_path = ['/content/drive/MyDrive/김원/Datas/Cream_dataset_v1.csv',
             '/content/drive/MyDrive/김원/Datas/Essence_dataset_v1.csv',
             '/content/drive/MyDrive/김원/Datas/Lotion_dataset_v1.csv',
             '/content/drive/MyDrive/김원/Datas/Mist_dataset_v1.csv',
             '/content/drive/MyDrive/김원/Datas/Skin_dataset_v1.csv']
dataframes = []

for file in file_path:
    df = pd.read_csv(file)
    dataframes.append(df)

raw = pd.concat(dataframes, ignore_index=True)
df = raw.copy()

In [20]:
df.head()

,Unnamed: 0,name,brand,price,sale_price,picture,url,volume,skin_type,ingredient,review
0,0.0,ahc유스래스팅리얼아이크림포페이스스페셜링클케어,AHC,23000,16900.0,https://image.oliveyoung.co.kr/uploads/images/...,https://www.oliveyoung.co.kr/store/G.do?goodsN...,본품: 아이크림 35ml / 증정품: 본품 동일 아이크림 7ml * 1ea,모든 피부용,"포트마리골드단백질추출물, 락토바실러스발효용해물, 글리세린, 다이프로필렌글라이콜, 사...",['세안 혹은 샤워 후 얼굴에 전체적으로 바르고 있습니다. 자극 없이 순해서 좋어요...
1,1.0,아비브수분초히알루론크림하이드레이팅팟,아비브,35000,35000.0,https://image.oliveyoung.co.kr/uploads/images/...,https://www.oliveyoung.co.kr/store/G.do?goodsN...,80ml (+수분초 패드 25ml/10pads 증정),모든 피부용,"정제수, 돌나물추출물, 글리세린, 세틸에틸헥사노에이트, 카프릴릭/카프릭트라이글리세라...","['ㅜㅜ강추.. 재발 사보셔요!!! 수분크림 유목민 탈출했엉요!!', '사용하면 피..."
2,2.0,ootdpm오버나잇아이크림,OOTD,30000,30000.0,https://image.oliveyoung.co.kr/uploads/images/...,https://www.oliveyoung.co.kr/store/G.do?goodsN...,25G,모든 피부,"정제수, 부틸렌글라이콜, 글리세린, 카프릴릭/카프릭트라이글리세라이드, 해바라기씨오일...","['지성 복합성에 너무좋아요 있던 주름도 사라집니다\\n향도 좋아요', '자기전에 ..."
3,3.0,ootdam인텐스아이세럼,OOTD,33000,17900.0,https://image.oliveyoung.co.kr/uploads/images/...,https://www.oliveyoung.co.kr/store/G.do?goodsN...,30g,모든 피부,"정제수, 글리세린, 프로필렌글라이콜, 세틸에틸헥사노에이트, 하이드로제네이티드폴리데센...",['너무나 잘 쓰고 있어요!\\n발림성도 너무나 좋고 바르고 나서도 가벼운 느낌이라...
4,4.0,dr다룸베리어크림,다룸,28000,19600.0,https://image.oliveyoung.co.kr/uploads/images/...,https://www.oliveyoung.co.kr/store/G.do?goodsN...,75g,모든 피부용,정제수@글리세린@카프릴릴메치콘@디프로필렌글라이콜@이소아밀라우레이트@펜틸렌글라이콜@1...,['코시국이라 마스크를 쓰고 다녀서 그런지 얼굴 피부가 예민해져서 붉어지고 좁쌀여드...

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 778 entries, 0 to 777
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  512 non-null    float64
 1   name        778 non-null    object
 2   brand       778 non-null    object
 3   price       778 non-null    object
 4   sale_price  778 non-null    object
 5   picture     778 non-null    object
 6   url         778 non-null    object
 7   volume      778 non-null    object
 8   skin_type   778 non-null    object
 9   ingredient  778 non-null    object
 10  review      778 non-null    object
dtypes: float64(1), object(10)
memory usage: 67.0+ KB

In [21]:
df['review_list'] = df['review'].apply(lambda x: x.split(','))

In [22]:
df['review_list'].head()

0    [['세안 혹은 샤워 후 얼굴에 전체적으로 바르고 있습니다. 자극 없이 순해서 좋어...
1    [['ㅜㅜ강추.. 재발 사보셔요!!! 수분크림 유목민 탈출했엉요!!',  '사용하면...
2    [['지성 복합성에 너무좋아요 있던 주름도 사라집니다\\n향도 좋아요',  '자기전...
3    [['너무나 잘 쓰고 있어요!\\n발림성도 너무나 좋고 바르고 나서도 가벼운 느낌이...
4    [['코시국이라 마스크를 쓰고 다녀서 그런지 얼굴 피부가 예민해져서 붉어지고 좁쌀여...
Name: review_list, dtype: object

In [23]:
len(df['review_list'])

778

In [30]:
# 중복 제거 및 Null 값 제거
df.drop_duplicates(subset=['review_list'], inplace=True)
df.dropna(subset=['review_list'], inplace=True)

In [25]:
df.drop(columns='Unnamed: 0', inplace = True)

In [26]:
df['review_list'][0]

["['세안 혹은 샤워 후 얼굴에 전체적으로 바르고 있습니다. 자극 없이 순해서 좋어요'",
 " '한달 사용 리뷰입니다. 추천드립니다. 좋은상품입니다.'",
 " '매달 살 정도로 합리적인 가격과 좋은 제품을 만나게 해주셔서 감사하고 꾸준한 품질관리 해주는만큼 믿고 사게 되는 것 같아요'",
 " '눈가에 주름이 생기는거 같아 아이크링 유명한걸로\\\\n또세일하길래 구매했어요\\\\n효과가 좋았으면해요'",
 " '처음 써보는 건데 아직 특별한 점은 잘 못 느끼겠어요 좀 더 써봐야 할 듯해요'",
 " '발림성 좋고 끈적임이 없어서 무난하게 사용하기 좋은 거 같아요!'",
 " '이제품 몇년간 진짜 꾸준히 사용중인데 좋아요 눈가 미간 팔짜주름 목주름등등 저는 전체적으로 다 펴 바르는데\\\\n너무 촉촉하고 좋아요 끈적임도 많이 없고 수분감도 있어서 쓰기\\\\n딱 좋습니다\\\\n발림성도 촉촛해서 너무 좋고 눈가에 자극 또한 없어서 쓰기 편해요'",
 " '동생이 써보고싶다고 사봤는데 역시 좋은 거 같아요~ 부드럽고 좋네용'",
 " '자극없이 순하고 촉촉해서 믿고 사는 제품입니다!\\\\n자극없이 순하고 촉촉해서 믿고 사는 제품입니다!'",
 " '여기 브랜드 제품의 아이크림은 꾸준히 사용 중이에요 촉촉하고 무겁지 않아서 너무 마음에 들어요'",
 " '조금씩 사용해서 그런지 큰 효과는 안나타나서 더 꾸준히 사용해 보겠습니다.'",
 " '보습도 좋고 향도 좋고 무엇보다 순해서 좋은 것 같야요 엄마 선뮬 해드렸는데 좋아하셨습다'",
 " '무난하게 사용하기 좋은 아이크림 입니다! 주름 개선도 좋고 끈적거리지 않아서 좋네요!'",
 " '아이크림으로ㅠ유명한 에이에이치씨 이번에 원플러스 원으로 잘 샀습ㅋ'",
 " '외국에 사는 친구 선물로 구매했어요 (｡･･｡) ..! 좋습니다'",
 " '오랫만에 구매해봤어요. 아직 사용전이긴한데 예전 빨강색이였을때에도 자극없이 괜찮앗아서 다시 한번 써보려구요.'",
 " '촉촉하고 페이스 겸용되니까 편함!!!\\\\n끈적임도 없고 발림성이 좋아서 소량만 발라도 됨.\\\\n자극은 거의 없었음. 빨간색이랑 큰 차이는 없지만 번갈아서 써보게 된ㄷr..'",
 " '아이크림 중에 저렴하고 브랜드여서 선물용으로 구매했어요'",
 " '무난하게 꾸준히 쓰기 좋은 제품같아요\\\\n눈 뒷꼬리쪽 주름이 좋아졌어요~'",
 " '워낙 아이크림이 유명한 브랜드이니까요~ 순해서 얼굴 전체어 바르고있어요'",
 " '이거 진짜 좋아요.. 이 크림 바르면 피부 좋다는 얘기 꼭 들어요 며칠안쓰다가 생각나서 바로 다시 구매했어요'",
 " '아이케어 하기 좋고 눈주변만 아니라 얼굴에 바르기에도 좋아요'",
 " '너무 좋은 제품입니다 보습력도 뛰어나고\\\\n벌써 몇통째 구매인지 모르겠네요\\\\n심지어 빅세일날 사서 싸게 잘산고같아요\\\\n휴대하기도 편하고 하루종일 촉촉하게 유지되네요\\\\n다른분들애게 강력추천 합니다'",
 " '이거 정말 좋아요!! 예전에 샘플로 사용해보고 좋았어서 잘 사용했던 기억이 있어서 본품으로 구매했어요 ㅎㅎ 쫀쫀하고 자극없어서 좋아용'",
 " '마침",
 ' 아이크림이 동나서',
 ' 올리브영에 구경갔다가 세일하니',
 ' 요거다!!하고 바로 지른 나만의 아이크림.. 워낙 유명한 제품이라 말모말모..!???ㅎㅎㅎ 진짜 꽤 괜찮았다. 성분도 뭐',
 ' 괜찮겠지!!??? 촉촉이 아이크림',
 ' 넘 좋아 헤헤~~~ 일단',
 ' 기대!♡ 그럼',
 ' 한달 사용후 후기 남기겠씀',
 '',
 '',
 "!!'",
 " '예전에 잘 썼었던 기억이 있어서 재구매했어요 ㅎㅎ 리뉴얼 된 거 같은데 여전히 좋은 거 같아용'",
 " '쫀쫀하게 잘 발리는 제형이라서 좋더라구요\\\\n저희 엄마께서 항상 쓰시는 제품입니더'",
 " '음 안검내반 수술하느라 눈밑 주름이 심해져서 가성비 좋고",
 ' 수분감 있는 아이크림 찾아보다가',
 ' 이 제품이 얼굴 전체 사용을 강조하길래 한번 구매해봤어요! 근데 사실 딱히 좋은 점은 모르겠어요 ㅎㅎ.. 보습감을 주는 정도 그 이상 그 이하도 아닌거 같아요. 원래 유세린 아이크림 제품 꾸준히 썼는데 수술 부위에 자극될까봐',
 " 이 제품 새로 산건데 크게 나쁘지도 크게 좋지도 않은 무난템입니다 ㅎㅎ'",
 " '아직 2주밖에 안돼서 잘 모르겠는데 되직한 느낌인데 피부에 바르면 금방 스며들고 피부가 쫀쫀하면서 부드러워지는 느낌이예요~아마 꾸준히 바르면 효과있을거 같애요'",
 " '아이크림은 에이에이치씨가 제일 유명하길래\\\\n그냥 뚜준히 구입하고있어요'",
 " '젛아요 저렴하고 한번 써보기에 나쁘지안ㄹ은 것 같아요 추첞'",
 " '저번부터 사용중인데 좀 더 효과가 있기를 빌며 계속 사용중입니다'",
 " '이거 쓰고 피부가 도자기가 된 이후로 꾸준히 사용하고있고 28살인데 18살 소리듣고있습니다\\\\U0001faf6🏻\\\\n끝쪽이 넙적한 고무라서 뭔가 짜서 쓰기 좋아요\\\\n엄마께도 선물해드렸는데 엄마도 끝에만 이렇게 다르게해도 편하다고 만족하셨어요!'",
 " '굿굿 좋으오 ദ്ദി・ᴗ・)✧ ଘ(੭*ˊᵕˋ)੭* ੈ♡‧₊˚'",
 " '무난무난해요 따갑진 않은데 살짝 붉어지는 거 같기도 하고?'",
 " '부모님께 드리려구 샀습니다!\\\\n좋은건 사용해봐야 알 것 같아요'",
 " '매일매일 사용하고 있어요\\\\n기존에 쓰던 아이크림을 다써서 구매한건데\\\\n데일리로 아주 좋아요'",
 " '아이크림 찾다가 ahc꺼 좋다고 해서 삿는데 괜찮네요 눈가 주름에 발라주고 잇어요'",
 " '향이 약간 맘에 안 들긴 하는데 꾸준히 바르고는 있어요. 효과가 있는진 모르겠지만 발라보고는 있슴다'",
 " '부모님 선물로 드리고 한 달 지났는데 잘 쓰고 계셔요!! 확실히 뭔가 주름이 준듯'",
 " '아이크림용으로 사용하고 있어요!! 할인 자주자주 해주세용'",
 " '사실 큰 변화는 없고 아이크림은 꾸준히 발라주면서 눈가주름이 더 생기지 않게 방지하려고 바르는 거라 용량도 많고 가격도 저렴해서 매일매일 바르기 좋아영'",
 " '얼굴 전체에 사용 가능한 아이크림이라 더 좋아요\\\\n어릴 때 부터 주름 예방 시작'",
 " '솔직히 주름에 큰 효과가 잘 모르겠어요 그치만 저번에 산 거 다 쓰고 또 구매하러 왔습니다 너무 무거운 제형이 아니라서 눈가뿐만 아니라 평소에 이마 팔자주름까지 바르기 정말 좋아요! 수분감도 충분하고 끈적임도 없어서 여름에도 큰 불쾌감 없이 사용 중입니다!'",
 " '눈밑 주름 부자인 저에겐 하나의 사랑같은 템…\\\\n잠 자기 전에 발라주기 딱 좋구 오래 쓰면 주름 개선이 보여서 넘무 조아염 🥰🥰\\\\n벌써 3통째 비우는 중 ..'",
 " '사워 후 얼굴 전체적으로 골고루 바르고 있습니다. 순해서 좋아요'",
 " '자극없이 순하고 보습에 좋아요 수분충전할수있어요 요새 엄청 건조해서 ㅜㅜ'",
 " '아이크림 무난하게 쓰기 좋은게 여기꺼여서 꾸준하기 쓰고있음'",
 " '기존에 쓰고 있던 라인은 없어서 가장 구매율이 높은걸로 구매했어요\\\\n역시 아이크림은 ahc'",
 " '조금 게으르게 발라서 잘 모르겠어요 그래도 꾸준히 발라볼게요'",
 " '일단 자극없고 워낙 아이크림에 유명한브랜드이니 믿고써봅니다'",
 " '눈밑 주름좀 지우려고 구매했습니다. 꾸준히 발라서효과 있었으면 해요'",
 " '잘발려용 밀착력도 좋고 완전 강추!!완전 이뻐용 다들 꼭사세용..'",
 " '솔직히… 아이크림을 찾던 찰나 저렴해서 구입했지만… 기능면으로는 며칠 안써서 아직 잘 모르겠고 얼굴 전체에 바를 수 있단 점과 보습에 아주 좋고 화장도 잘먹어 대만족임 재구매 의사 매우 많음'",
 " '항상 잘 사용하고 있습니다ㅏ항상 잘 사용하고 있습니다^_^'",
 " 'Ahc는 워낙 유명하니 믿고 구매했습니다. 눈가에 자꾸 미세하게 주름이 생기는것 같아 자기전 바르고 자는데 기분탓인지 좀 좋아진것 같기도 하고 그래요.'",
 " '오!! 이거 촉촉하니 좋아요 냄새도 너무 좋아요~ㅗㅎㅎㅎ'",
 " '한달 넘에 잘사용하고있습니다\\\\n큰 불편감없이 만족스러워요'",
 " 'AHC는 제품가격도 부담없고 성분도알차고 이래저래 가성비면으로 좋아요'",
 " '추천 받아서 구매했는데 좋아요! 다음에 또 구매해서 쓸 거 같아용'",
 " '아이크림은 ahc제품이 가성비가장 좀아서 듬뿍바르고 있어요'",
 " '무난하게 쓰기 좋은 것 같아요~ 효과도 있었으면 좋겠네요~~'",
 " '선물용으로 구매했는데 받은 분이 촉촉하고 좋다고 만족하셨습니다.'",
 " '아이크림은 계속 이 브랜드만 쓰는거같습ㄴ다...가격이 저렴해여'",
 " '팁 부분이 신기하게 생김 아이크림 처음이라 어떻게 해야할지 잘 모르겠지만 아직 트러블은 안 올라옴'",
 " '걍 무난템.. 진찌 무난해요 도움이 되는지도 머르겠도 그냉 쏘쏘~ 괜츤ㄹ네요 ㅎㅎ'",
 " '아직 큰 효과는 모르겠는데 일단 보습이 잘 되고 순해서 안심해서 잘 바르는 중입니다.'",
 " '눈가 아이크림으로 사용하는데 주름에 좋아요! 잘 사용하고 있어요'",
 " '얼굴전체 바르는 아이크림이라 좋아요 바르고 자면 촉촉하고 당김없이 사용할수있어요'",
 " '이게 구성이 좋아서 그런가 저희 어머니가 자주 재구매하세요 근데 특별한 효과보다는 그냥 관리차원'",
 " '제품이 부드럽게 발려서 그 점은 만족스럽구요",
 "\\\\n앞으로도 잘 사용할 것 같네요ㅎㅎ'",
 " '즉각 주름개선 효과는 보기 어렵지만 잔 주름이 옅어지는 것은 확인 할 수 있었습니다\\\\n아침보단 밤에 바르는게 나을것같아요 유분감있는 제형이라서요 ! 데일리 케어로 좋습니다'",
 " '무엇보다 향이 넘 좋은 아이크림!\\\\n향수로 내주면 좋겠다..\\\\n살짝 되직한 편이라 잘 펴발라줘야된다. 그래도 부드럽게 잘 발라진다. 가성비템이라 추천! 효과는 딱히 모르겠지만 페이스용이라 부담없이 바르기 좋다.'",
 " '복합성피부인 저한테 그리고 진정이 필요할때 좋아요 열을 낮춰줘요'",
 " '저는 그냥 얼굴전체 목전체 듬뿍 바릅니닷\\\\nAhc는 고런 맛이죠'",
 " 'AHC 선크림 초록이가 젤 잘맞아요. 피부가 예민한 편인데 이 크림은 무겁지 않고 촉촉해요'",
 " '리뉴얼 된거같아서 구매해봤어요~ 무난하게 사용하기좋아요'",
 " '눈에 들어가면 한참 따가워서 주의가 필요할 듯 합니다. 그것말고눈 괜찮아요 눈가에 바르고 팔자주름 부분에도 바르고 해서 2통째 씁니다'",
 " '눈가에 자극없이 흡수가 되고 발림성이 좋아요\\\\n무난하게 사용하기 좋네요'",
 " '동생이 좋다고 구매했는데 저도 미니미한거줘서 사용중입니당ㅋㅋ']"]

In [27]:
# 텍스트 정규화 함수
def text_normalization(text):
    text = text.lower()  # 소문자 변환
    text = re.sub(r'\d+', '', text)  # 숫자 제거
    text = re.sub(r'\s+', ' ', text)  # 여러 개의 공백을 하나의 공백으로 치환
    text = re.sub(r'[^\w\s]', '', text)  # 특수 문자 제거
    return text

In [28]:
# review_list의 각 요소에 대해 text_normalization 적용
import re
df['review_list'] = df['review_list'].apply(lambda reviews: [text_normalization(review) for review in reviews])

In [32]:
!pip install konlpy

Collecting konlpy
  Downloading konlpy-0.6.0-py2.py3-none-any.whl.metadata (1.9 kB)
Collecting JPype1>=0.7.0 (from konlpy)
  Downloading JPype1-1.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from konlpy) (4.9.4)
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.10/dist-packages (from konlpy) (1.26.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from JPype1>=0.7.0->konlpy) (24.1)
Downloading konlpy-0.6.0-py2.py3-none-any.whl (19.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 58.6 MB/s eta 0:00:00
Downloading JPype1-1.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (488 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 36.5 MB/s eta 0:00:00
Installing collected packages: JPype1, konlpy
Successfully installed JPype1-1.5.0 konlpy-0.6.0

In [33]:
# 불용어 제거 함수
from konlpy.tag import Okt
def remove_stopwords(text, stopwords):
    okt = Okt()
    words = okt.morphs(text)
    words = [word for word in words if word not in stopwords]
    return ' '.join(words)

In [34]:
# 불용어 리스트
stopwords = ['이', '그', '저', '것', '수', '들', '등', '을', '를', '은', '는', '에', '의', '가', '로', '에서']

In [35]:
# review_list의 각 요소에 대해 불용어 제거 적용
df['review_list'] = df['review_list'].apply(lambda reviews: [remove_stopwords(review, stopwords) for review in reviews])

In [37]:
# 모든 리뷰 리스트를 하나의 리스트로 축소
all_reviews = [review for sublist in df['review_list'] for review in sublist]

In [41]:
len(all_reviews)

79853

In [42]:
# 새로운 데이터프레임 생성
df_review_list = pd.DataFrame(all_reviews, columns=['review_list'])

In [43]:
df_review_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79853 entries, 0 to 79852
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_list  79853 non-null  object
dtypes: object(1)
memory usage: 624.0+ KB

In [44]:
df_review_list.to_csv('/content/drive/MyDrive/김원/Datas/preprecessed_total_reviews.csv')

In [ ]:
df_review_list = pd.read_csv('/content/drive/MyDrive/김원/Datas/preprecessed_total_reviews.csv')

In [45]:
# 데이터타입 변환
df_review_list['review_list'] = df_review_list['review_list'].astype(str)

In [46]:
len(df_review_list['review_list'])

79853

In [ ]:
df_review_list['review_list']

0             세안 혹은 샤워 후 얼굴 전체 적 으로 바르고 있습니다 자극 없이 순해서 좋어요
1                          한 달 사용 리뷰 입니다 추천 드립니다 좋은 상품 입니다
2        매달 살 정도 합리 적 인 가격 과 좋은 제품 만나게 해주셔서 감사하고 꾸준한 품질...
3        눈가 주름 생기는거 같아 아이크 링 유명한 걸 n 또세 일하길래 구매 했어요 n 효...
4            처음 써 보는 건데 아직 특별한 점 잘 못 느끼겠어요 좀 더 써 봐야 할 듯 해요
                               ...
79848    n 각질 에도 좋고 일단 순한 성분 진정 되는 느낌 좋아서 매일 쓰고 있습니다 n ...
79849                          재구매 했어용 피부 편안한 느낌 적 인 느낌 ㅎㅎ
79850    기초 케어 라인 전부 후시 다인 으로 통일 해서 쓰고 있는데 유수 분 밸런스 조절 ...
79851    후시 다인 제품 n 사용 해보고 반해가지고 n 요즘 매 일 매일 사용 하다 보 니깐...
79852    물 토너 인데 도 불구 하고 발림 성 뻐덕뻐덕해 요 n 자기 전 스킨 케어 썼더니 ...
Name: review_list, Length: 79853, dtype: object

In [47]:
# 데이터프레임을 데이터셋으로 변환
from datasets import Dataset

dataset = Dataset.from_pandas(df_review_list)

In [48]:
dataset

Dataset({
    features: ['review_list'],
    num_rows: 79853
})

In [49]:
# 모델 이름과 토크나이저 초기화
model_name = 'kykim/bert-kor-base'
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [50]:
# 토크나이저 함수 정의
def tokenizer_func(examples):
    return tokenizer(
        examples['review_list'],
        padding='max_length',
        max_length=256,
        truncation=True
    )

In [51]:
tokenized_review_list = dataset.map(tokenizer_func, batched=True)

Map:   0%|          | 0/79853 [00:00<?, ? examples/s]

In [52]:
# 데이터셋 크기 확인
dataset_size = len(tokenized_review_list)
train_num_samples = min(79853, dataset_size)  # 데이터셋 크기를 넘지 않도록 설정

In [53]:
txts_td = tokenized_review_list.select(range(train_num_samples))

In [54]:
txts_td

Dataset({
    features: ['review_list', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 79853
})

In [55]:
preds_txts = pipe(txts_td['review_list'])

In [56]:
preds_txts_df = pd.DataFrame(preds_txts)

In [57]:
preds_txts_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79853 entries, 0 to 79852
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   79853 non-null  object
 1   score   79853 non-null  float64
dtypes: float64(1), object(1)
memory usage: 1.2+ MB

In [ ]:
preds_txts_df.head()

   label     score
0      1  0.978707
1      1  0.961900
2      1  0.988946
3      1  0.900858
4      1  0.547701

In [58]:
preds_txts_df['label'] = preds_txts_df['label'].map({'LABEL_1':1, 'LABEL_0':0})

In [59]:
review_labeling_df = pd.DataFrame(txts_td)

In [60]:
review_labeling_df.head()

,review_list,input_ids,token_type_ids,attention_mask
0,세안 혹은 샤워 후 얼굴 전체 적 으로 바르고 있습니다 자극 없이 순해서 좋어요,"[2, 17951, 15427, 15767, 7876, 14369, 14433, 6...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,한 달 사용 리뷰 입니다 추천 드립니다 좋은 상품 입니다,"[2, 7653, 3118, 13978, 15282, 14295, 14195, 18...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, ..."
2,매달 살 정도 합리 적 인 가격 과 좋은 제품 만나게 해주셔서 감사하고 꾸준한 품질...,"[2, 18925, 4890, 14061, 17530, 6016, 5925, 140...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,눈가 주름 생기는거 같아 아이크 링 유명한 걸 n 또세 일하길래 구매 했어요 n 효...,"[2, 31115, 18622, 18644, 8132, 15565, 13999, 8...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4,처음 써 보는 건데 아직 특별한 점 잘 못 느끼겠어요 좀 더 써 봐야 할 듯 해요,"[2, 14121, 5301, 15024, 20217, 14189, 16250, 6...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [61]:
preds_txts_df = pd.concat([preds_txts_df, review_labeling_df], axis=1)
preds_txts_df

,label,score,review_list,input_ids,token_type_ids,attention_mask
0,1,0.978707,세안 혹은 샤워 후 얼굴 전체 적 으로 바르고 있습니다 자극 없이 순해서 좋어요,"[2, 17951, 15427, 15767, 7876, 14369, 14433, 6...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,1,0.961900,한 달 사용 리뷰 입니다 추천 드립니다 좋은 상품 입니다,"[2, 7653, 3118, 13978, 15282, 14295, 14195, 18...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, ..."
2,1,0.988946,매달 살 정도 합리 적 인 가격 과 좋은 제품 만나게 해주셔서 감사하고 꾸준한 품질...,"[2, 18925, 4890, 14061, 17530, 6016, 5925, 140...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,1,0.900858,눈가 주름 생기는거 같아 아이크 링 유명한 걸 n 또세 일하길래 구매 했어요 n 효...,"[2, 31115, 18622, 18644, 8132, 15565, 13999, 8...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4,1,0.547701,처음 써 보는 건데 아직 특별한 점 잘 못 느끼겠어요 좀 더 써 봐야 할 듯 해요,"[2, 14121, 5301, 15024, 20217, 14189, 16250, 6...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
...,...,...,...,...,...,...
79848,1,0.952779,n 각질 에도 좋고 일단 순한 성분 진정 되는 느낌 좋아서 매일 쓰고 있습니다 n ...,"[2, 2054, 16948, 32135, 14410, 14405, 20212, 1...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
79849,1,0.984017,재구매 했어용 피부 편안한 느낌 적 인 느낌 ㅎㅎ,"[2, 15307, 36934, 8114, 14081, 17467, 14066, 6...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, ..."
79850,1,0.964095,기초 케어 라인 전부 후시 다인 으로 통일 해서 쓰고 있는데 유수 분 밸런스 조절 ...,"[2, 16144, 16862, 15953, 16047, 7876, 8118, 31...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
79851,1,0.978629,후시 다인 제품 n 사용 해보고 반해가지고 n 요즘 매 일 매일 사용 하다 보 니깐...,"[2, 7876, 8118, 3110, 8159, 13996, 2054, 13978...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
79852,0,0.960740,물 토너 인데 도 불구 하고 발림 성 뻐덕뻐덕해 요 n 자기 전 스킨 케어 썼더니 ...,"[2, 4223, 17638, 22673, 3238, 16158, 14042, 17...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [62]:
preds_txts_df.drop(columns=['input_ids', 'token_type_ids', 'attention_mask'], inplace=True)

In [63]:
preds_txts_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79853 entries, 0 to 79852
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   label        79853 non-null  int64
 1   score        79853 non-null  float64
 2   review_list  79853 non-null  object
dtypes: float64(1), int64(1), object(1)
memory usage: 1.8+ MB

In [64]:
preds_txts_df.to_csv('/content/drive/MyDrive/김원/Datas/total_review_labeling_without_clssification.csv')

In [65]:
# 같은 행에서 df['label']의 값이 1이면 df['review_list']에 [긍정]이라는 텍스트를 추가
preds_txts_df.loc[preds_txts_df['label'] == 1, 'review_list'] = '[긍정] ' + preds_txts_df['review_list']

# 같은 행에서 df['label']의 값이 0이면 df['review_list']에 [부정]이라는 텍스트를 추가
preds_txts_df.loc[preds_txts_df['label'] == 0, 'review_list'] = '[부정] ' + preds_txts_df['review_list']

preds_txts_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79853 entries, 0 to 79852
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   label        79853 non-null  int64
 1   score        79853 non-null  float64
 2   review_list  79853 non-null  object
dtypes: float64(1), int64(1), object(1)
memory usage: 1.8+ MB

In [66]:
preds_txts_df.reset_index(drop=True)

       label     score                                        review_list
0          1  0.978707  [긍정] 세안 혹은 샤워 후 얼굴 전체 적 으로 바르고 있습니다 자극 없이 순해서 좋어요
1          1  0.961900               [긍정] 한 달 사용 리뷰 입니다 추천 드립니다 좋은 상품 입니다
2          1  0.988946  [긍정] 매달 살 정도 합리 적 인 가격 과 좋은 제품 만나게 해주셔서 감사하고 꾸...
3          1  0.900858  [긍정] 눈가 주름 생기는거 같아 아이크 링 유명한 걸 n 또세 일하길래 구매 했어...
4          1  0.547701  [긍정] 처음 써 보는 건데 아직 특별한 점 잘 못 느끼겠어요 좀 더 써 봐야 할 ...
...      ...       ...                                                ...
79848      1  0.952779  [긍정] n 각질 에도 좋고 일단 순한 성분 진정 되는 느낌 좋아서 매일 쓰고 있습...
79849      1  0.984017                   [긍정] 재구매 했어용 피부 편안한 느낌 적 인 느낌 ㅎㅎ
79850      1  0.964095  [긍정] 기초 케어 라인 전부 후시 다인 으로 통일 해서 쓰고 있는데 유수 분 밸런...
79851      1  0.978629  [긍정] 후시 다인 제품 n 사용 해보고 반해가지고 n 요즘 매 일 매일 사용 하다...
79852      0  0.960740  [부정] 물 토너 인데 도 불구 하고 발림 성 뻐덕뻐덕해 요 n 자기 전 스킨 케어...

[79853 rows x 3 columns]

In [67]:
# 긍정 댓글의 수
preds_txts_df.loc[preds_txts_df['label'] ==1].count()

label          66061
score          66061
review_list    66061
dtype: int64

In [68]:
# 부정 댓글의 수
preds_txts_df.loc[preds_txts_df['label'] ==0].count()

label          13792
score          13792
review_list    13792
dtype: int64

In [69]:
preds_txts_df.to_csv('/content/drive/MyDrive/김원/Datas/total_review_labeling_with_classification.csv')